# Generated by Django 5.1.1 on 2024-10-08 10:18

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutes', '0002_album_band_concert_interview_musician_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Títol')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='InterestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Títol')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('url', models.URLField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'Punt interès',
                'verbose_name_plural': "Punts d'interès",
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom')),
                ('name2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom')),
                ('name3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='TrailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Títol')),
            ],
            options={
                'verbose_name': 'Tipologia itinerari',
                'verbose_name_plural': "Tipologia d'itineraris",
            },
        ),
        migrations.RemoveField(
            model_name='musician',
            name='band',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='band',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='band',
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Títol')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='Publicat')),
                ('distance', models.FloatField(blank=True, help_text='Distància en km', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Distància')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Durada en minuts', null=True, verbose_name='Durada')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trails', to='rutes.campus', verbose_name='Campus')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutes.trailtype', verbose_name='Tipologia')),
            ],
            options={
                'verbose_name': 'Itinerari',
                'verbose_name_plural': 'Itineraris',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Títol')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geometria')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Ordre')),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='rutes.trail', verbose_name='Trail')),
            ],
            options={
                'verbose_name': 'Punt',
                'verbose_name_plural': 'Punts',
                'unique_together': {('trail', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
    ]
