# Generated by Django 5.1.1 on 2024-10-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutes', '0004_rename_name1_person_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
